name: Deploy

on:
  push:
    branches:
      - v1
  sync:
    branches:
      - v1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy to Server
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no root@ssh.ryzentx.com "cd ~/htdocs/ataa.ryzentx.com/Ataa-Server && git pull origin v1 && pm2 restart ataa-server"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ssh.ryzentx.com
